### ISSUE TITLE
Reroll with Schips and Erschwernis

### ISSUE THREAD

**Issue by kuhlo** [Plushtoast/dsa5-foundryVTT#276] opened 2021-04-12 19:37 UTC
If you miss a roll and deselected e.g. Belastung in the roll window and reroll with Schips it seems Belastung is readded in the roll.

Expectation: Same behaviour as original roll.

**Comment by Plushtoast** [comment] 2021-04-12 19:46
The roll keeps the actor state at the moment of the roll. Later changes are and will not be taken into consideration.
If you want to remove the belastung afterwards, edit the roll and change the modifier accordingly.

**Comment by Plushtoast** [comment] 2021-04-13 12:26
Duplicate of #247

**Closed** 2021-04-13 12:26 UTC
Labels: duplicate
