### ISSUE TITLE
FW values: unlocked in locked charsheet and accepts any values

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#45] opened 2021-02-11 09:57 UTC
**Describe the bug**
Module 1.1.0
If you lock the character sheet, the fields for values (abilities, spells etc.) are still open and can be edited.
When changing values directly in the field, it is possible to set any value (not sure if this is a bug or by design to overcome the restrictions of the rules if wanted).
If you change values directly in the field, then change them later on with + and - buttons, they sometimes snap back to old values entered manually.

**To Reproduce**
Select one talent, Switch between locked/unlocked sheet, change values with +/- symbols and directly in the field, roll inbetween each change and check against what value it rolls.

**Expected behavior**
Changes for values should be possible or not possible, independent of how you set them.
Validity check should either happen or not, independent of how you set a value ("maximaler fertigkeitswert erreicht...")

**Desktop (please complete the following information):**
win10, running as GM

**Additional context**
Suggestions:
- Lock/Unlock FW fields via separate option ("Change Values directly - recommended for char creation only" or similar)
- When locked, only allow changes via symbols +/-
- Allow to ignore rule limitations via options (select, if you want to hard-limit values, only show a warning, or don't check at all, for different areas like magic, abilities etc.)

**Comment by Plushtoast** [comment] 2021-02-11 10:46
Thanks for your feedback.
The unrestricted change of the values in the input fields is intentional. It is supposed to act as a fallback, when any bug or issues breaks the automatic adventure point calculation for advancements in skills and anything like that. Also it is supposed to give the players full control, if they use houserules or other things that require a manual configuration( as you said overcome the restrictions). So limits will only be calculated through -+. For ease of use the lock button could also lock all input fields. That's probably more consistent.

Changing values directly and then using +- resulting in a snap back is a bug. I ll change that for the next patch.

**Comment by Plushtoast** [comment] 2021-02-12 07:05
So the snap back should be fixed with the patch.

But I won't do anything about your other proposals. I don't want to have too many options for this and that.
It is working as intended. The advancement buttons are optional, not the manual definition of skills.

Thanks for your input. Maybe it'll be important in the future.

**Closed** 2021-02-12 16:14 UTC
Labels: bug
