### ISSUE TITLE
Add the option to modify single attributes for a talent check

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#106] opened 2021-02-20 22:02 UTC
**Is your feature request related to a problem? Please describe.**
Many Abilities modify a single Attribute for a given Talent Check

**Describe the solution you'd like**
On the Check Window, add the option to modify all three attribute checks manually.

**Comment by Plushtoast** [comment] 2021-02-21 08:52
Duplicate of #94

**Closed** 2021-02-21 14:59 UTC
Labels: duplicate
