### ISSUE TITLE
Ammunition: Add Effect(s)

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#510] opened 2021-07-16 14:49 UTC
It would be nice to be able to have different ammo types with different changes in how they work, fe: -1 TP, +1 FK or =1w3 TP etc.

For special arrows, it would also be nice to be able to transfer effects, fe. stunning arrows, or added poison and the like

**Comment by Plushtoast** [comment] 2021-07-16 18:11
Ah finde das duplicat grad nicht
Sobald armory 2 dran ist

**Comment by Plushtoast** [comment] 2021-07-17 14:32
Duplicate of #408

**Closed as completed** 2021-11-14 09:58 UTC
Labels: duplicate
