### ISSUE TITLE
GM Menu: cannot use the tavern generator

### ISSUE THREAD

**Issue by Nostros-BE** [Plushtoast/dsa5-foundryVTT#708] opened 2021-11-21 09:01 UTC
**Describe the bug**
With the module Master's toolbox, the tavern generator does not generate anything but an error:
![image](https://user-images.githubusercontent.com/64594454/142756007-611d90c7-cd61-4233-b33f-271dc5f068a1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/64594454/142756001-e04498a3-5327-4a9b-bc43-da4a0306b8b1.png)

**Desktop (please complete the following information):**
- self-hosting server
- Foundry vtt v0.8.9
- all required modules active

**Comment by Plushtoast** [comment] 2021-11-21 09:05
Duplicate of #707

**Closed as completed** 2021-12-07 14:59 UTC
Labels: bug, duplicate
