### ISSUE TITLE
You can create and have multiple amunitions but no Special Amunition

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-foundryVTT#602] opened 2021-09-28 16:37 UTC
**Is your feature request related to a problem? Please describe.**
I was adding a new Arrow ammunition item, but I cannot add a TP or effect modifier to the ammunition, so it is only a fancy name for the same arrow threat is already present. I would have expected to be able to create ammunition as described in: https://www.ulisses-regelwiki.de/besondere-munitionsarten.html. Do I have to wait for Aventuria Armory II?

**Describe the solution you'd like**
I would like to be able to add combat related effects like TP, FK, Reichweite as well as appying effects to targets that are being hit, similar to the spell "Humuspfeil".

**Describe alternatives you've considered**
We could very well go simple first and only allow TP/FK modifications from an effect field instead of having more complex interaction

**Comment by Plushtoast** [comment] 2021-09-28 17:21
Duplicate of #408

**Comment by mckee14** [comment] 2021-09-28 18:03
Workaround: copy the bow and modify the TP and effects on the weapon. Give
each weapon its corrsponding arrows, so you can keep track of the quantity.

In combat, just switch the weapons instead of the arrows (and name them
accordingly)

Mind, only one bow should have weight, else the weight calculation is off.

Plushtoast ***@***.***> schrieb am Di., 28. Sept. 2021, 19:22:

**Comment by Plushtoast** [comment] 2021-09-29 10:49
Die armory 2 ist auch schon gut vorangekommen.
Wird bestimmt auch nicht mehr ewig dauern

**Comment by Plushtoast** [comment] 2021-09-29 17:47
Mit der Verbesserung des Feuer Zustands mit nächsten Patch, kann sowieso niemand mehr ohne Feuerpfeile spielen...

**Closed as completed** 2021-11-14 09:57 UTC
Labels: duplicate
